### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by beingmerry** [tophergates/mobile-web-specialist#6]
Hi there!
I was going to utilize your notes as a framework for my own note taking during the course.  I was wondering if you could add a license to your work? (so I am not technically stealing it)
Thanks,
Ben

A personal favorite: https://choosealicense.com/licenses/mit/

https://choosealicense.com/
https://help.github.com/articles/licensing-a-repository/

**Comment by tophergates** [comment]
Absolutely! I will add the MIT license tonight. Please use, share, edit, etc. as you please.
