### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by Synchrony001** [tophergates/mobile-web-specialist#8]
I just started **Google Africa Challenge Scholarship: Mobile Web Specialist** and your notes have been a big help. 

I just thought to say **Thank you**.  I hope you do more.

**Comment by tophergates** [comment]
Congratulations and good luck to you in the scholarship! I am current in the second phase of the scholarship here in the United States. Please feel free to submit pull requests to add or update any information/resources that you feel might help others.
